-- ====================================================================
-- ESQUEMA DE BASE DE DATOS SUPABASE - TABLA EXCLUSIVA PARA CONTACTOS
-- ====================================================================
-- Este archivo contiene UNICAMENTE la estructura SQL para la tabla `contacts`
-- que permite almacenar los contactos guardados por la PWA.

CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Politica para permitir Lectura, Insercion, Actualizacion y Eliminacion Publica
DROP POLICY IF EXISTS "Public full access contacts" ON contacts;
CREATE POLICY "Public full access contacts" ON contacts FOR ALL USING (true) WITH CHECK (true);
