-- ====================================================================
-- ESQUEMA DE BASE DE DATOS SUPABASE - TABLA EXCLUSIVA PARA NOTAS
-- ====================================================================
-- Este archivo contiene UNICAMENTE la estructura SQL para la tabla `notes`
-- que permite almacenar notas tipo Post-it creadas manualmente o mediante el bot.

-- Crear Tabla de Notas tipo Post-it
CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  color TEXT DEFAULT '#fef08a', -- Color pastel predeterminado
  image_url TEXT, -- Soporte para fotos/imagenes adjuntas
  drawing_data TEXT, -- Data URL del dibujo en canvas
  width INT DEFAULT 260,
  height INT DEFAULT 260,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

-- Politica para permitir Lectura, Insercion, Actualizacion y Eliminacion Publica
DROP POLICY IF EXISTS "Public full access notes" ON notes;
CREATE POLICY "Public full access notes" ON notes FOR ALL USING (true) WITH CHECK (true);
