-- ====================================================================
-- ESQUEMA DE BASE DE DATOS SUPABASE (TABLAS Y POLITICAS DE ACCESO)
-- ====================================================================

-- 1. Tabla para Base de Conocimiento (FAQs, Sheets, Archivos)
CREATE TABLE IF NOT EXISTS knowledge (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE knowledge ENABLE ROW LEVEL SECURITY;

-- Politica para permitir Lectura, Insercion, Actualizacion y Eliminacion
DROP POLICY IF EXISTS "Public full access knowledge" ON knowledge;
CREATE POLICY "Public full access knowledge" ON knowledge FOR ALL USING (true) WITH CHECK (true);


-- 2. Tabla para Alarmas y Recordatorios Inteligentes
CREATE TABLE IF NOT EXISTS alarms_reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL, -- 'alarma' o 'recordatorio'
  name TEXT NOT NULL,
  message TEXT,
  schedule_mode TEXT DEFAULT 'days', -- 'days' o 'date'
  days INT[], -- Ej: [1,2,3,4,5]
  specific_date DATE,
  time TIME NOT NULL,
  timezone TEXT DEFAULT 'local',
  use_range BOOLEAN DEFAULT FALSE,
  range_start TIME,
  range_end TIME,
  range_limit INT DEFAULT 1,
  voice TEXT DEFAULT 'default',
  sound TEXT DEFAULT 'Predeterminado',
  sound_url TEXT,
  volume FLOAT DEFAULT 0.8,
  repeat BOOLEAN DEFAULT TRUE,
  repeat_interval INT DEFAULT 5,
  max_repeats INT DEFAULT 3,
  interaction TEXT DEFAULT 'button',
  active BOOLEAN DEFAULT TRUE,
  last_executed TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE alarms_reminders ENABLE ROW LEVEL SECURITY;

-- Politica para permitir Lectura, Insercion, Actualizacion y Eliminacion
DROP POLICY IF EXISTS "Public full access alarms" ON alarms_reminders;
CREATE POLICY "Public full access alarms" ON alarms_reminders FOR ALL USING (true) WITH CHECK (true);


-- 3. Tabla para Notas tipo Post-it
CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  color TEXT DEFAULT '#fef08a', -- Color pastel predeterminado
  image_url TEXT,
  drawing_data TEXT, -- Data URL del dibujo en canvas
  width INT DEFAULT 240,
  height INT DEFAULT 240,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

-- Politica para permitir Lectura, Insercion, Actualizacion y Eliminacion
DROP POLICY IF EXISTS "Public full access notes" ON notes;
CREATE POLICY "Public full access notes" ON notes FOR ALL USING (true) WITH CHECK (true);


-- 4. Tabla para Ubicaciones GPS de Dispositivos (PWA para 2 personas)
CREATE TABLE IF NOT EXISTS locations (
  device_id TEXT PRIMARY KEY,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  address TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;

-- Politica para permitir Lectura, Insercion, Actualizacion y Eliminacion Publica
DROP POLICY IF EXISTS "Public full access locations" ON locations;
CREATE POLICY "Public full access locations" ON locations FOR ALL USING (true) WITH CHECK (true);
